server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
       development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmfz
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB